## Trends in the regional funding distribution and the public participation in cultural heritage projects ##

In Italy, every region has different amount of funding and level of participation in cultural activities.
This project aims to discover how the public funding distributed in the last 10 years(2014-2024) is, and how the trend of visitors changes over time.

**THE DATA ANALYSIS**

In [59]:
#Libraries to install in case needed:
#!pip install pandas
#!pip install os
#!pip install glob
#!pip install seaborn

In [60]:
import pandas as pd

project_20 = pd.read_csv("data/progetti_esteso_CULTURA_TURISMO_2014-2020_20250430.csv", sep=';', low_memory=False)
project_20

,COD_LOCALE_PROGETTO,CUP,OC_TITOLO_PROGETTO,OC_SINTESI_PROGETTO,OC_LINK,OC_COD_CICLO,OC_DESCR_CICLO,OC_COD_TEMA_SINTETICO,OC_TEMA_SINTETICO,COD_GRANDE_PROGETTO,...,COD_INDICATORE_3,DESCR_INDICATORE_3,UNITA_MISURA_INDICATORE_3,PROGRAMMATO_INDICATORE_3,REALIZZATO_INDICATORE_3,COD_INDICATORE_4,DESCR_INDICATORE_4,UNITA_MISURA_INDICATORE_4,PROGRAMMATO_INDICATORE_4,REALIZZATO_INDICATORE_4
0,6IGRUEE497_98540_13,D36J20001910005,MANUTENZIONE STRAORDINARIA CON SOSTITUZIONE IN...,Manutenzione straordinaria per efficientamento...,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6IGRUEF426_12855,D42H23000340001,LAVORI DI ADEGUAMENTO/RISTRUTTURAZIONE DI LOCA...,LAVORI DI ADEGUAMENTO/RISTRUTTURAZIONE DI LOCA...,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6IGRUEF877_22485,B69J20002290001,GRACIELA ANA DESIMONI*AVVISO PUBBLICO PER LA C...,GRACIELA ANA DESIMONI*AVVISO PUBBLICO PER LA C...,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6IGRUEF934_15284,G57H20001950001,Realizzazione locale ristorazione nell'edifici...,Realizzazione locale ristorazione nell'edifici...,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6IGRUEF934_15853,G57H21001140001,REALIZZAZIONE LOCALE RISTORAZIONE NELL'EDIFICI...,REALIZZAZIONE LOCALE RISTORAZIONE NELL'EDIFICI...,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14737,6IGRUEC768_54319,I84E21024540005,Contributo a fondo perduto per le spese di ges...,Contributo a fondo perduto,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14738,6IGRUEC999_60696,F24E21001130001,Contributo alle piccole e micro imprese comuni...,Contributo per spese di gestione e di investim...,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14739,6IGRUED691_92635,H81G22000290005,CONTRIBUTO A FONDO PERDUTO A SOSTEGNO DEL COMM...,CONTRIBUTO A FONDO PERDUTO A SOSTEGNO DEL COMM...,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14740,6IGRUED811_83907,B48E22000100001,FONDO COMUNI MARGINALI ANNUALITA' 2021: ADEGUA...,INTERVENTO DI ADEGUAMENTO FUNZIONALE DEL RICOV...,https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14741,6IGRUEE297_74691,B87D22000350005,"INVESTIMENTO INFRASTRUTTURALE, MANUTENZIONE ST...","INVESTIMENTO INFRASTRUTTURALE, MANUTENZIONE ST...",https://opencoesione.gov.it/it/dati/progetti/6...,2,Ciclo di programmazione 2014-2020,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
project_27 = pd.read_csv("data/progetti_esteso_CULTURA_TURISMO_2021-2027_20250430.csv", sep=';', low_memory=False)
project_27

,COD_LOCALE_PROGETTO,CUP,OC_TITOLO_PROGETTO,OC_SINTESI_PROGETTO,OC_LINK,OC_COD_CICLO,OC_DESCR_CICLO,OC_COD_TEMA_SINTETICO,OC_TEMA_SINTETICO,COD_GRANDE_PROGETTO,...,COD_INDICATORE_3,DESCR_INDICATORE_3,UNITA_MISURA_INDICATORE_3,PROGRAMMATO_INDICATORE_3,REALIZZATO_INDICATORE_3,COD_INDICATORE_4,DESCR_INDICATORE_4,UNITA_MISURA_INDICATORE_4,PROGRAMMATO_INDICATORE_4,REALIZZATO_INDICATORE_4
0,6TO1121730/1,H37H21001230002,1121730/1-Finanziamento progetti a valere su F...,FSC 2021/2027 - Impegno di spesa nei confronti...,https://opencoesione.gov.it/it/dati/progetti/6...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6TO1121730/2,H15F21000290002,1121730/2-Finanziamento progetti a valere su F...,FSC 2021/2027 - Impegno di spesa nei confronti...,https://opencoesione.gov.it/it/dati/progetti/6...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6TO1189319/2,H78C18000080004,1189319/2-Nuovo Polo Culturale edificio storic...,Interventi finanziati a valere sull'anticipazi...,https://opencoesione.gov.it/it/dati/progetti/6...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6TO1189319/3,C57H21000820005,1189319/3-,Interventi finanziati a valere sull'anticipazi...,https://opencoesione.gov.it/it/dati/progetti/6...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6TO1189319/4,C52E18000090004,1189319/4-Teatro Manzoni ¿ Interventi di adegu...,Interventi finanziati a valere sull'anticipazi...,https://opencoesione.gov.it/it/dati/progetti/6...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,1SI31644,F25F21001690006,RAGUSA. Restauro e recupero funzionale a Teatr...,RAGUSA. Restauro e recupero funzionale a Teatr...,https://opencoesione.gov.it/it/dati/progetti/1...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
868,1SI33307,I83B19000340006,progetto esecutivo per la tutela e la valorizz...,PARCO URBANO E PARCO PIANETTE*VIA CONTRADE CAN...,https://opencoesione.gov.it/it/dati/progetti/1...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
869,2LIFSC21/27-8.1.1-CLA01,G41E19000000004,VALORIZZAZIONE E RESTAURO EX CONVENTO DELLE CL...,riqualificazione e messa in sicurezza antisism...,https://opencoesione.gov.it/it/dati/progetti/2...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
870,2LIFSC21/27-8.1.5-MUR01,G43D19000040006,RECUPERO E VALORIZZAZIONE MURA OTTOCENTESCHE -...,Recupero e valorizzazione delle mura ottocente...,https://opencoesione.gov.it/it/dati/progetti/2...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
871,2LIFSC21/27-8.1.5-SP4-1,G49G20000140006,PROGETTO RIQUALIFICAZIONE DEL PARCO DELLA RIME...,"Restauro delle mura ottocentesche, nuovo impia...",https://opencoesione.gov.it/it/dati/progetti/2...,3,Ciclo di programmazione 2021-2027,6,Cultura e turismo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
#studying the metadata file we extracted the name of the columns containing data useful to our research
project_20 = project_20[['CUP','DATA_INIZIO_PREV_STUDIO_FATT','OC_DATA_INIZIO_PROGETTO','OC_DATA_FINE_PROGETTO_EFFETTIVA','DEN_REGIONE','DEN_PROVINCIA','DEN_COMUNE','FINANZ_TOTALE_PUBBLICO','FINANZ_STATO_ESTERO','FINANZ_PRIVATO']]
project_27 = project_27[['CUP', 'DATA_INIZIO_PREV_STUDIO_FATT','OC_DATA_INIZIO_PROGETTO','OC_DATA_FINE_PROGETTO_EFFETTIVA','DEN_REGIONE','DEN_PROVINCIA','DEN_COMUNE','FINANZ_TOTALE_PUBBLICO','FINANZ_STATO_ESTERO','FINANZ_PRIVATO']]

#merge the two datasets and drop duplicates on project id ('CUP')
all_projects = pd.concat([project_20, project_27], ignore_index=True)
all_projects = all_projects.drop_duplicates(subset=['CUP'], keep='first')
all_projects

,CUP,DATA_INIZIO_PREV_STUDIO_FATT,OC_DATA_INIZIO_PROGETTO,OC_DATA_FINE_PROGETTO_EFFETTIVA,DEN_REGIONE,DEN_PROVINCIA,DEN_COMUNE,FINANZ_TOTALE_PUBBLICO,FINANZ_STATO_ESTERO,FINANZ_PRIVATO
0,D36J20001910005,NaN,20201113.0,20211108.0,LOMBARDIA,BRESCIA,Lavenone,"21329,99","0,00","0,00"
1,D42H23000340001,NaN,20240418.0,20240628.0,CAMPANIA,SALERNO,Montano Antilia,"53876,46","0,00","0,00"
2,B69J20002290001,NaN,20201229.0,20211019.0,LOMBARDIA,COMO,Nesso,"639,87","0,00","0,00"
3,G57H20001950001,NaN,20210210.0,20210711.0,SARDEGNA,ORISTANO,Norbello,"17540,00","0,00","0,00"
4,G57H21001140001,NaN,20210430.0,20211001.0,SARDEGNA,ORISTANO,Norbello,"17540,00","0,00","0,00"
...,...,...,...,...,...,...,...,...,...,...
15609,F25F21001690006,20231129.0,20211222.0,NaN,SICILIA,RAGUSA,Ragusa,"2000000,00","0,00","0,00"
15610,I83B19000340006,20190227.0,20241205.0,NaN,SICILIA,PALERMO,Gangi,"412543,00","0,00","0,00"
15611,G41E19000000004,20190225.0,20181207.0,NaN,LIGURIA,LA SPEZIA,La Spezia,"900000,00","0,00","0,00"
15612,G43D19000040006,20190411.0,20190917.0,20230530.0,LIGURIA,LA SPEZIA,La Spezia,"1500000,00","0,00","0,00"
15613,G49G20000140006,20200713.0,20201127.0,20230530.0,LIGURIA,LA SPEZIA,La Spezia,"726000,00","0,00","0,00"

In [63]:
#select columns containing datetime data and convert format accordingly
date_columns = ['DATA_INIZIO_PREV_STUDIO_FATT','OC_DATA_INIZIO_PROGETTO','OC_DATA_FINE_PROGETTO_EFFETTIVA']
all_projects[date_columns] = (all_projects[date_columns].apply(lambda col: pd.to_datetime(col.astype('Int64').astype(str), format='%Y%m%d', errors='coerce')))

#sort dataset by chronological order
all_projects = all_projects.sort_values(by=date_columns, ascending=[True, True, True], na_position='last').reset_index(drop=True)
all_projects.to_csv("data/open_coesione.csv", index=False, encoding="utf-8")
all_projects

,CUP,DATA_INIZIO_PREV_STUDIO_FATT,OC_DATA_INIZIO_PROGETTO,OC_DATA_FINE_PROGETTO_EFFETTIVA,DEN_REGIONE,DEN_PROVINCIA,DEN_COMUNE,FINANZ_TOTALE_PUBBLICO,FINANZ_STATO_ESTERO,FINANZ_PRIVATO
0,H72B04000040001,1991-04-27,2004-08-01,2007-11-08,LAZIO,LATINA,Norma,"1000000,00","0,00","0,00"
1,H72B07000040004,1991-04-27,2008-07-31,2012-12-16,LAZIO,LATINA,Norma,"1200000,00","0,00","0,00"
2,F91E05000040002,1991-10-25,1991-10-25,1993-07-10,MOLISE,CAMPOBASSO,Montorio nei Frentani,"635433,57","0,00","0,00"
3,E19D03000100001,1992-03-30,2004-04-29,2009-07-02,LAZIO,RIETI,Concerviano,"1900000,00","0,00","0,00"
4,E37B03000110001,1993-03-30,1993-03-30,2006-03-10,TOSCANA,LUCCA,Piazza al Serchio,"504800,00","0,00","0,00"
...,...,...,...,...,...,...,...,...,...,...
14735,G79I24000450001,NaT,NaT,NaT,SICILIA,PALERMO,Palermo,"2200000,00","0,00","0,00"
14736,H87B22000100001,NaT,NaT,NaT,ABRUZZO,CHIETI,Fallo,"2560000,00","0,00","0,00"
14737,I29G24000110002,NaT,NaT,NaT,MARCHE,FERMO,Servigliano,"45000,00","0,00","0,00"
14738,I39G22000740006,NaT,NaT,NaT,ABRUZZO,L'AQUILA,Scurcola Marsicana,"1140000,00","0,00","0,00"
14739,I72H24000740006,NaT,NaT,NaT,PIEMONTE,ASTI,Berzano di San Pietro,"93775,00","0,00","0,00"

In [64]:
import os
import glob

#function to extract the data from a list of csv files where only the year changes in the files name
#aim to have a table where the rows are in ascending chronological order and the columns are the italian regions

def transform_table(file):
    year = os.path.basename(file).split("_")[2]
    #detect header of table
    with open(file, "r", encoding = "latin-1") as f:
        for i,line in enumerate(f):
            if line.startswith("Regione"):
                header_row = i
                break
    visitors = pd.read_csv(file, skiprows = header_row, sep=";", encoding="latin-1")
    #one row and one column both named "Totale complessivo"
    visitors.rename(columns={"Totale complessivo":"Totale_regione"}, inplace= True) 
    # invert rows and columns
    visitors = visitors.set_index("Regione").T
    
    visitors.dropna(axis=1, how="all", inplace= True)
    visitors.dropna(axis=0, how="all", inplace= True)
    
    # rename the rows to add the year
    visitors.index = [f"{month}_{year}" for month in visitors.index]

    return visitors

In [65]:
# apply to all visitatori files and create a unique table
files = glob.glob("data/musei_tavola5_*_visitatori.csv")
total_visitors = []
for f in files:
    total_visitors.append(transform_table(f))
    
# merge along rows
output_visitors = pd.concat(total_visitors)
output_visitors.to_csv("data/mic_visitors.csv", encoding="utf-8")
output_visitors

Regione,ABRUZZO,BASILICATA,CALABRIA,CAMPANIA,EMILIA ROMAGNA,FRIULI-VENEZIA GIULIA,LAZIO,LIGURIA,LOMBARDIA,MARCHE,MOLISE,PIEMONTE,PUGLIA,SARDEGNA,TOSCANA,UMBRIA,VENETO,Totale complessivo
Gennaio_2014,6.122,4.181,16.976,197.190,36.377,18.550,865.763,5.415,67.115,13.144,1.894,111.967,13.324,5.076,282.604,7.975,41.233,1.694.906
Febbraio_2014,5.605,5.491,13.454,202.937,29.683,16.985,916.680,4.787,63.906,10.628,1.913,69.131,11.348,4.379,297.647,7.770,45.624,1.707.968
Marzo_2014,13.076,11.560,28.421,416.848,70.014,98.857,1.379.306,13.308,112.345,33.341,3.945,142.107,32.020,18.264,516.217,17.179,85.082,2.991.890
Aprile_2014,21.496,30.553,47.039,802.855,162.044,148.327,1.977.764,15.971,191.948,75.658,13.443,253.492,87.587,46.792,753.184,33.473,107.840,4.769.466
Maggio_2014,24.086,33.920,60.602,921.493,146.706,164.710,1.999.835,21.267,195.425,63.481,14.584,270.117,111.596,71.860,766.530,32.411,106.962,5.005.585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Settembre_2024,15.516,23.551,63.958,976.910,79.265,137.173,2.698.479,20.127,184.979,49.169,9.051,169.518,65.220,84.734,833.872,37.680,90.779,5.539.981
Ottobre_2024,12.280,24.039,40.670,1.079.998,73.088,126.379,2.741.673,17.168,186.734,34.493,5.855,191.800,67.078,53.350,801.097,24.263,98.371,5.578.336
Novembre_2024,13.003,20.862,23.540,565.180,70.091,90.672,1.886.847,13.539,143.122,30.460,5.269,225.665,35.012,14.995,577.729,23.131,70.311,3.809.428
Dicembre_2024,9.318,11.216,20.307,456.209,53.000,93.956,1.748.928,11.233,126.851,27.816,3.020,212.946,22.961,9.579,554.001,19.163,55.309,3.435.813
Totale_regione_2024,192.101,231.147,583.983,10.288.474,967.169,1.543.789,29.729.231,222.420,2.179.931,555.975,94.735,2.558.188,654.033,558.238,9.106.895,348.329,1.035.453,60.850.091

In [66]:
import pandas as pd
import os
import glob

def transform_income(file):
    year = os.path.basename(file).split("_")[2]
    #detect header of table
    with open(file, "r", encoding = "latin-1") as f:
        for i,line in enumerate(f):
            if line.startswith("Regione"):
                header_row = i
                break
    money = pd.read_csv(file, skiprows = header_row, sep=";", encoding="latin-1")
    
    money.dropna(axis=1, how="all", inplace= True)
    money.dropna(axis=0, how="any", inplace= True)
    
    money = money[["Regione","Totale complessivo"]]
    money.rename(columns={"Totale complessivo": f"Introiti_{year}"}, inplace=True)

    return money

In [67]:
# apply to all introiti files and create a unique table
tables_income = glob.glob("data/musei_tavola5_*_introiti.csv")
dfs = [transform_income(path) for path in tables_income]

# unisci tutti i DataFrame sulle regioni
output_income = dfs[0]
for d in dfs[1:]:
    output_income = output_income.merge(d, on="Regione", how="outer")
output_income = output_income[output_income["Regione"] != "Totale complessivo"]

output_income

,Regione,Introiti_2014,Introiti_2015,Introiti_2016,Introiti_2017,Introiti_2018,Introiti_2019,Introiti_2020,Introiti_2021,Introiti_2022,Introiti_2023,Introiti_2024
0,ABRUZZO,"61.642,00","70.532,00","144.988,00","118.299,00","146.490,00","166.313,00","113.900,00","112.670,00","267.494,00","293.534,00","412.475,00"
1,BASILICATA,"135.802,50","186.339,50","201.068,00","197.857,75","219.145,25","268.357,75","130.156,25","160.133,00","229.306,00","300.444,00","428.448,00"
2,CALABRIA,"477.460,00","408.853,00","826.893,50","922.318,50","920.820,00","830.624,00","350.858,00","615.850,00","946.060,00","1.132.969,00","1.394.737,00"
3,CAMPANIA,"31.364.258,37","35.485.065,23","40.165.583,52","45.322.835,41","58.015.681,19","60.214.623,62","11.537.616,60","21.000.421,22","53.499.304,93","74.230.512,96","80.316.519,46"
4,EMILIA ROMAGNA,"1.576.305,50","1.760.796,50","2.219.286,25","2.602.786,00","2.859.961,60","3.190.301,86","1.229.433,56","1.988.934,02","2.942.267,66","3.238.546,38","3.406.107,04"
5,FRIULI-VENEZIA GIULIA,"786.722,00","1.151.233,50","1.456.039,00","1.765.735,00","1.725.868,50","1.596.536,50","645.008,50","947.056,50","1.760.810,50","2.458.941,50","2.881.182,00"
6,LAZIO,"58.153.039,00","62.911.364,50","67.616.298,00","75.849.708,00","84.317.158,50","87.338.260,50","16.540.368,00","28.068.765,50","90.491.113,00","120.495.222,00","154.764.990,00"
7,LIGURIA,"142.429,40","182.674,90","390.503,55","433.861,50","463.885,80","420.896,80","132.542,10","144.478,50","499.228,00","703.071,50","784.053,80"
8,LOMBARDIA,"5.003.515,20","5.986.736,50","7.993.159,35","9.194.753,90","9.503.485,45","10.447.982,70","2.911.571,60","5.098.833,20","11.343.755,40","13.010.511,50","14.178.965,90"
9,MARCHE,"901.488,50","986.158,50","1.356.043,50","1.422.302,25","1.902.582,00","2.185.658,50","1.036.188,50","1.273.583,00","1.749.433,50","1.764.104,00","2.243.382,00"
10,MOLISE,"26.039,00","28.464,00","48.693,50","75.943,00","92.029,00","94.393,00","103.941,00","110.734,00","132.020,00","156.499,00","319.349,00"
11,PIEMONTE,"6.709.213,90","10.931.980,29","13.367.382,44","13.414.330,03","13.352.880,96","13.113.004,27","3.747.064,25","6.175.643,65","12.944.397,62","16.058.406,99","15.581.675,30"
12,PUGLIA,"825.313,00","1.190.167,25","1.396.514,75","1.576.480,50","1.841.963,00","1.801.071,00","386.438,00","794.298,00","1.899.834,00","2.324.717,00","2.919.301,00"
13,SARDEGNA,"1.149.698,50","1.233.460,00","1.412.742,50","1.609.809,50","1.569.103,50","1.551.457,50","513.672,50","966.153,50","1.643.337,00","1.976.033,60","2.156.586,10"
14,TOSCANA,"25.231.128,00","29.902.126,25","31.085.537,75","35.472.108,50","48.969.049,00","55.180.157,70","11.849.965,90","19.325.643,70","49.929.892,35","71.192.030,10","94.811.132,90"
16,UMBRIA,"419.804,95","467.004,66","567.165,19","544.629,48","668.290,32","701.186,25","360.622,72","262.533,21","705.362,50","1.336.876,50","1.197.004,25"
17,VENETO,"2.546.841,92","2.611.458,31","3.192.844,96","3.392.006,76","3.062.704,87","3.309.806,34","993.750,08","1.586.471,12","3.607.516,32","3.215.743,68","4.208.435,99"

In [68]:
import pandas as pd

file_path = "data/open_coesione.csv"
df = pd.read_csv(file_path, dtype=str)

# FINANZ_TOTALE_PUBBLICO column
fin_col = "FINANZ_TOTALE_PUBBLICO"

# --- Convert financing to numeric ---
df[fin_col] = (
    df[fin_col].astype(str)
    .str.replace(r"[^\d,.\-]", "", regex=True)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
)
df[fin_col] = pd.to_numeric(df[fin_col], errors="coerce")

#  Drop rows without province info 
df = df[df['DEN_PROVINCIA'].notna() & (df['DEN_PROVINCIA'].str.strip() != "")]

# Handle multi-region 
df['num_regions'] = df['DEN_REGIONE'].str.split(":::").str.len()
df_expanded = df.assign(DEN_REGIONE=df['DEN_REGIONE'].str.split(":::")).explode('DEN_REGIONE')
df_expanded['DEN_REGIONE'] = df_expanded['DEN_REGIONE'].str.strip()
df_expanded[fin_col] = df_expanded[fin_col] / df_expanded['num_regions']

# Normalize region names 
region_map = {
    "TRENTINO-ALTO ADIGE": "TRENTINO-ALTO ADIGE/SÜDTIROL",
    "TRENTINO ALTO ADIGE": "TRENTINO-ALTO ADIGE/SÜDTIROL",
    "VALLE D’AOSTA": "VALLE D'AOSTA",
    "FRIULI VENEZIA GIULIA": "FRIULI-VENEZIA GIULIA",
}
df_expanded['DEN_REGIONE'] = df_expanded['DEN_REGIONE'].replace(region_map)

# Drop non-regions
to_drop = ["PAESI EUROPEI", "AMBITO NAZIONALE"]
df_expanded = df_expanded[~df_expanded['DEN_REGIONE'].isin(to_drop)]

# Extract project start year 
df_expanded['OC_DATA_INIZIO_PROGETTO'] = pd.to_datetime(
    df_expanded['OC_DATA_INIZIO_PROGETTO'], errors="coerce"
)
df_expanded['YEAR'] = df_expanded['OC_DATA_INIZIO_PROGETTO'].dt.year.astype('Int64')
df_expanded = df_expanded[(df_expanded['YEAR'] >= 2014) & (df_expanded['YEAR'] <= 2024)]

# Aggregate funding by Region × Year
funding_matrix = df_expanded.groupby(['DEN_REGIONE', 'YEAR'])[fin_col].sum().reset_index()

In [69]:
# pivot: regioni sulle righe, anni sulle colonne
funding_wide = funding_matrix.pivot(
    index="DEN_REGIONE",
    columns="YEAR",
    values=fin_col
)

# rinomina le colonne come Fondi_2014, Fondi_2015, ...
funding_wide.columns = [f"Fondi_{int(c)}" for c in funding_wide.columns]

# resetta l'indice per avere 'Regione' come colonna
funding_wide = funding_wide.reset_index().rename(columns={"DEN_REGIONE": "Regione"})

# merge orizzontale con la tabella degli introiti
merged = output_income.merge(funding_wide, on="Regione", how="outer")

# ordina le colonne nel formato Regione - Introiti_2014 - Fondi_2014 - ...
merged = merged.reindex(
    ["Regione"] +
    sorted([c for c in merged.columns if c != "Regione"], key=lambda x: (x[-4:], x))
, axis=1)

merged.to_csv("data/income&funding.csv", encoding="utf-8", index=False)
merged

,Regione,Fondi_2014,Introiti_2014,Fondi_2015,Introiti_2015,Fondi_2016,Introiti_2016,Fondi_2017,Introiti_2017,Fondi_2018,...,Fondi_2020,Introiti_2020,Fondi_2021,Introiti_2021,Fondi_2022,Introiti_2022,Fondi_2023,Introiti_2023,Fondi_2024,Introiti_2024
0,ABRUZZO,4.422272e+06,"61.642,00",1.336223e+07,"70.532,00",5.555200e+07,"144.988,00",1.421057e+07,"118.299,00",1.857946e+07,...,4.781431e+06,"113.900,00",3459923.35,"112.670,00",8.055261e+06,"267.494,00",855168.81,"293.534,00",4782465.08,"412.475,00"
1,BASILICATA,1.225995e+07,"135.802,50",4.702406e+06,"186.339,50",4.767180e+07,"201.068,00",4.095908e+07,"197.857,75",3.663281e+07,...,1.207484e+07,"130.156,25",5625670.52,"160.133,00",8.389892e+06,"229.306,00",7632916.31,"300.444,00",1546340.13,"428.448,00"
2,CALABRIA,4.013252e+05,"477.460,00",NaN,"408.853,00",4.935166e+07,"826.893,50",3.933068e+07,"922.318,50",6.925908e+07,...,3.469685e+07,"350.858,00",70436070.95,"615.850,00",6.468718e+07,"946.060,00",6142398.38,"1.132.969,00",1624975.00,"1.394.737,00"
3,CAMPANIA,2.385599e+07,"31.364.258,37",2.784502e+07,"35.485.065,23",4.558519e+08,"40.165.583,52",1.554002e+08,"45.322.835,41",1.107498e+08,...,8.619085e+07,"11.537.616,60",86428063.35,"21.000.421,22",4.043417e+08,"53.499.304,93",49859456.73,"74.230.512,96",59099313.64,"80.316.519,46"
4,EMILIA ROMAGNA,NaN,"1.576.305,50",NaN,"1.760.796,50",NaN,"2.219.286,25",NaN,"2.602.786,00",NaN,...,NaN,"1.229.433,56",NaN,"1.988.934,02",NaN,"2.942.267,66",NaN,"3.238.546,38",NaN,"3.406.107,04"
5,EMILIA-ROMAGNA,7.000000e+04,NaN,2.874000e+07,NaN,8.727373e+07,NaN,5.018357e+07,NaN,6.841976e+07,...,5.988277e+06,NaN,3860239.10,NaN,1.464786e+06,NaN,349609.90,NaN,NaN,NaN
6,FRIULI-VENEZIA GIULIA,NaN,"786.722,00",1.025973e+06,"1.151.233,50",5.618914e+05,"1.456.039,00",7.079137e+06,"1.765.735,00",5.365684e+07,...,1.576555e+06,"645.008,50",NaN,"947.056,50",3.338350e+06,"1.760.810,50",NaN,"2.458.941,50",NaN,"2.881.182,00"
7,LAZIO,NaN,"58.153.039,00",NaN,"62.911.364,50",1.031108e+08,"67.616.298,00",5.947984e+05,"75.849.708,00",3.122025e+07,...,3.433683e+06,"16.540.368,00",27253141.23,"28.068.765,50",2.638405e+07,"90.491.113,00",NaN,"120.495.222,00",NaN,"154.764.990,00"
8,LIGURIA,7.119359e+05,"142.429,40",1.853274e+06,"182.674,90",2.496279e+07,"390.503,55",7.500000e+04,"433.861,50",2.005837e+07,...,8.842610e+05,"132.542,10",NaN,"144.478,50",NaN,"499.228,00",205000.00,"703.071,50",3400000.00,"784.053,80"
9,LOMBARDIA,NaN,"5.003.515,20",3.085210e+05,"5.986.736,50",3.273265e+07,"7.993.159,35",2.839395e+07,"9.194.753,90",3.250940e+07,...,3.506612e+05,"2.911.571,60",429478.40,"5.098.833,20",1.465529e+06,"11.343.755,40",62460978.30,"13.010.511,50",358000.00,"14.178.965,90"
10,MARCHE,5.385728e+06,"901.488,50",1.691045e+06,"986.158,50",3.358957e+06,"1.356.043,50",6.233062e+05,"1.422.302,25",3.070397e+07,...,7.574916e+06,"1.036.188,50",9559277.62,"1.273.583,00",9.806179e+05,"1.749.433,50",4851723.49,"1.764.104,00",NaN,"2.243.382,00"
11,MOLISE,1.504286e+06,"26.039,00",1.668959e+06,"28.464,00",1.513504e+06,"48.693,50",3.520400e+06,"75.943,00",1.100566e+07,...,1.863370e+07,"103.941,00",4910333.60,"110.734,00",6.644771e+06,"132.020,00",807562.38,"156.499,00",226000.00,"319.349,00"
12,PIEMONTE,2.265550e+06,"6.709.213,90",6.406684e+06,"10.931.980,29",4.907020e+07,"13.367.382,44",3.414058e+07,"13.414.330,03",1.195945e+07,...,3.981611e+06,"3.747.064,25",9453862.53,"6.175.643,65",1.448780e+07,"12.944.397,62",3924584.47,"16.058.406,99",10848814.10,"15.581.675,30"
13,PUGLIA,2.627733e+08,"825.313,00",3.049538e+07,"1.190.167,25",7.479153e+07,"1.396.514,75",6.077398e+07,"1.576.480,50",1.178281e+08,...,4.412076e+07,"386.438,00",18640478.88,"794.298,00",2.268960e+07,"1.899.834,00",6082738.10,"2.324.717,00",10764064.00,"2.919.301,00"
14,SARDEGNA,6.042260e+05,"1.149.698,50",8.827000e+05,"1.233.460,00",1.073189e+07,"1.412.742,50",3.936613e+07,"1.609.809,50",2.732514e+07,...,1.215310e+07,"513.672,50",4540751.78,"966.153,50",1.387465e+07,"1.643.337,00",5508761.00,"1.976.033,60",2424882.50,"2.156.586,10"
15,SICILIA,1.545267e+07,NaN,5.244855e+07,NaN,1.657014e+08,NaN,3.368511e+07,NaN,2.876557e+07,...,1.065849e+08,NaN,45561716.65,NaN,6.111574e+07,NaN,14900842.76,NaN,11162818.50,NaN
16,TOSCANA,5.290623e+07,"25.231.128,00",1.904920e+08,"29.902.126,25",1.442500e+07,"31.085.537,75",1.221733e+08,"35.472.108,50",3.432169e+07,...,4.192354e+05,"11.849.965,90",852053.00,"19.325.643,70",2.180498e+07,"49.929.892,35",11815981.22,"71.192.030,10",10640677.53,"94.811.132,90"
17,TRENTINO-ALTO ADIGE/SÜDTIROL,NaN,NaN,3.810666e+06,NaN,1.124658e+06,NaN,1.000000e+06,NaN,9.308200e+04,...,4.469748e+05,NaN,40000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,UMBRIA,5.462178e+06,"419.804,95",3.994971e+06,"467.004,66",1.112746e+07,"567.165,19",1.377339e+07,"544.629,48",8.450639e+06,...,1.133181e+07,"360.622,72",8585074.27,"262.533,21",5.616694e+06,"705.362,50",4302466.69,"1.336.876,50",NaN,"1.197.004,25"
19,VALLE D'AOSTA,NaN,NaN,3.150000e+05,NaN,6.386027e+06,NaN,1.330136e+07,NaN,9.015926e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,VENETO,1.972127e+07,"2.546.841,92",2.493250e+07,"2.611.458,31",1.592951e+07,"3.192.844,96",4.522684e+06,"3.392.006,76",9.646277e+06,...,1.740283e+06,"993.750,08",180986.50,"1.586.471,12",1.630093e+05,"3.607.516,32",129355.00,"3.215.743,68",2000000.00,"4.208.435,99"

**THE VISUALIZATION**

In [70]:
#Libraries to install in case needed:
#!pip install plotly
#!pip install seaborn
#!pip install matplotlib
#!pip install folium
#!pip install geopandas

In [71]:
import pandas as pd

df = pd.read_csv("data/open_coesione.csv")
df.head()

,CUP,DATA_INIZIO_PREV_STUDIO_FATT,OC_DATA_INIZIO_PROGETTO,OC_DATA_FINE_PROGETTO_EFFETTIVA,DEN_REGIONE,DEN_PROVINCIA,DEN_COMUNE,FINANZ_TOTALE_PUBBLICO,FINANZ_STATO_ESTERO,FINANZ_PRIVATO
0,H72B04000040001,1991-04-27,2004-08-01,2007-11-08,LAZIO,LATINA,Norma,"1000000,00","0,00","0,00"
1,H72B07000040004,1991-04-27,2008-07-31,2012-12-16,LAZIO,LATINA,Norma,"1200000,00","0,00","0,00"
2,F91E05000040002,1991-10-25,1991-10-25,1993-07-10,MOLISE,CAMPOBASSO,Montorio nei Frentani,"635433,57","0,00","0,00"
3,E19D03000100001,1992-03-30,2004-04-29,2009-07-02,LAZIO,RIETI,Concerviano,"1900000,00","0,00","0,00"
4,E37B03000110001,1993-03-30,1993-03-30,2006-03-10,TOSCANA,LUCCA,Piazza al Serchio,"504800,00","0,00","0,00"

**Italian Cultural Heritage Funding grouped by sources(public/private/foreign)** -fig.1.1

In [72]:
# fig.1.1

import pandas as pd
import plotly.graph_objects as go

# Load CSV
df = pd.read_csv("data/open_coesione.csv")


def parse_number(val):
    if pd.isna(val):
        return 0
    s = str(val).strip().replace("€", "").replace(" ", "")
    if "," in s and "." in s:
        s = s.replace(".", "").replace(",", ".")
    else:
        s = s.replace(",", ".")
    try:
        return float(s)
    except:
        return 0

def extract_year(date_str):
    if pd.isna(date_str):
        return None
    s = str(date_str)
    
    if len(s) >= 10 and s[4] == "-":
        return int(s[:4])
    
    if "/" in s and len(s.split("/")[-1]) == 4:
        return int(s.split("/")[-1])
    
    import re
    match = re.search(r"(19|20)\d{2}", s)
    return int(match.group(0)) if match else None


for col in ["FINANZ_TOTALE_PUBBLICO", "FINANZ_STATO_ESTERO", "FINANZ_PRIVATO"]:
    df[col] = df[col].apply(parse_number)


df["year"] = df["OC_DATA_INIZIO_PROGETTO"].apply(extract_year)


agg = df.groupby("year").agg({
    "FINANZ_TOTALE_PUBBLICO": "sum",
    "FINANZ_STATO_ESTERO": "sum",
    "FINANZ_PRIVATO": "sum"
}).reset_index()


agg["pubblico"] = agg["FINANZ_TOTALE_PUBBLICO"] / 1e6
agg["estero"]   = agg["FINANZ_STATO_ESTERO"] / 1e6
agg["privato"]  = agg["FINANZ_PRIVATO"] / 1e6

# --- Filter rules ---
agg = agg[(agg["year"] >= 1997) & (agg["year"] != 2025)]
agg = agg[(agg["pubblico"] > 0) | (agg["estero"] > 0) | (agg["privato"] > 0)]

fig = go.Figure()

fig.add_trace(go.Bar(
    x=agg["year"], y=agg["pubblico"],
    name="Pubblico", marker_color="#1976d2",
    hovertemplate="<b>%{x}</b><br>Pubblico: €%{y:.2f} M<extra></extra>"
))

fig.add_trace(go.Bar(
    x=agg["year"], y=agg["estero"],
    name="Estero", marker_color="#43a047",
    hovertemplate="<b>%{x}</b><br>Estero: €%{y:.2f} M<extra></extra>"
))

fig.add_trace(go.Bar(
    x=agg["year"], y=agg["privato"],
    name="Privato", marker_color="#ff7043",
    hovertemplate="<b>%{x}</b><br>Privato: €%{y:.2f} M<extra></extra>"
))


fig.update_layout(
    barmode="stack",
    xaxis=dict(title="Start Year", tickmode="linear", dtick=1, tickangle=-90),
    yaxis=dict(title="Funding (Million €)"),
    margin=dict(t=40, l=80, r=30, b=100),
    height=600,
    width=950
)
import plotly.io as pio
pio.renderers.default = "notebook" 

fig.show()

ModuleNotFoundError: No module named 'plotly'

**Italian Public Funding of Cultural Heritage grouped by Regions** - fig.2.1

In [ ]:
# fig.2.1

import pandas as pd
import geopandas as gpd
import folium
from branca.colormap import linear

# --- 1. Helper function to normalize region names ---
def normalize_region_name(name: str) -> str:
    if not isinstance(name, str):
        return ""
    normalized = "".join(ch for ch in name.lower() if ch.isalnum())
    if "trentino" in normalized:
        normalized = "trentinoaltoadige"
    if "valle" in normalized:
        normalized = "valledaosta"
    return normalized

# Load the data 
csv_file = "data/open_coesione.csv"
geojson_file = "data/italy_regions.geojson"

df = pd.read_csv(csv_file, dtype=str)
gdf = gpd.read_file(geojson_file)

# Clean and process funding data 
df["FINANZ_TOTALE_PUBBLICO"] = (
    df["FINANZ_TOTALE_PUBBLICO"]
    .fillna("0")
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

df["region_norm"] = df["DEN_REGIONE"].apply(normalize_region_name)

# Aggregate funding per region
region_data = df.groupby("region_norm")["FINANZ_TOTALE_PUBBLICO"].sum().to_dict()

# Normalize names in GeoDataFrame and join funding data 
if "name" in gdf.columns:
    name_col = "name"
elif "reg_name" in gdf.columns:
    name_col = "reg_name"
else:
    print("Available columns in GeoJSON:", gdf.columns)
    raise KeyError("Could not find a region name column (expected 'name' or 'reg_name').")

gdf["region_norm"] = gdf[name_col].apply(normalize_region_name)
gdf["funding"] = gdf["region_norm"].map(region_data).fillna(0)


#  Create color scale 
max_funding = gdf["funding"].max()
colormap = linear.YlOrRd_09.scale(0, max_funding)
colormap.caption = "Total Funding (€)"

# Initialize map 
m = folium.Map(location=[41.87194, 12.56738], zoom_start=5, tiles="cartodbpositron")

#  Add GeoJSON layer with style + popups 
folium.GeoJson(
    gdf,
    style_function=lambda feature: {
        "fillColor": colormap(feature["properties"]["funding"]),
        "color": "white",
        "weight": 2,
        "dashArray": "3",
        "fillOpacity": 0.7,
    },
    highlight_function=lambda feature: {
        "weight": 5,
        "color": "#666",
        "dashArray": "",
        "fillOpacity": 0.9,
    },
    tooltip=folium.GeoJsonTooltip(
    fields=["reg_name", "funding"],
    aliases=["Region:", "Total Funding (€):"],
    localize=True
),
).add_to(m)

# Add legend
colormap.add_to(m)

m

**Horizontal Barchart of Total Public Funding Allocated to Regions (2014-2024)** - fig.3

In [ ]:
# fig.3

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns

#  Load dataset 
file_path = "data/open_coesione.csv"
df = pd.read_csv(file_path, dtype=str)

#  Keep only relevant columns 
cols = [
    "CUP",
    "DATA_INIZIO_PREV_STUDIO_FATT",
    "OC_DATA_INIZIO_PROGETTO",
    "OC_DATA_FINE_PROGETTO_EFFETTIVA",
    "DEN_REGIONE",
    "FINANZ_TOTALE_PUBBLICO"
]
df = df[cols].copy()

# Normalize region names 
def normalize_region_name(name: str) -> str:
    if not isinstance(name, str):
        return ""
    normalized = "".join(ch for ch in name.lower() if ch.isalnum())
    if "trentino" in normalized or "bolzano" in normalized or "altoadige" in normalized:
        return "trentinoaltoadige"
    elif "friuli" in normalized:
        return "friuliveneziagiulia"
    elif "valledaosta" in normalized or "aoste" in normalized:
        return "valledaosta"
    elif "emiliaromagna" in normalized:
        return "emiliaromagna"
    elif "lombardia" in normalized:
        return "lombardia"
    elif "piemonte" in normalized:
        return "piemonte"
    elif "veneto" in normalized:
        return "veneto"
    elif "liguria" in normalized:
        return "liguria"
    elif "toscana" in normalized:
        return "toscana"
    elif "umbria" in normalized:
        return "umbria"
    elif "marche" in normalized:
        return "marche"
    elif "lazio" in normalized:
        return "lazio"
    elif "abruzzo" in normalized:
        return "abruzzo"
    elif "molise" in normalized:
        return "molise"
    elif "campania" in normalized:
        return "campania"
    elif "puglia" in normalized:
        return "puglia"
    elif "basilicata" in normalized:
        return "basilicata"
    elif "calabria" in normalized:
        return "calabria"
    elif "sicilia" in normalized:
        return "sicilia"
    elif "sardegna" in normalized:
        return "sardegna"
    return normalized

#  Apply normalization 
df["REGION_KEY"] = df["DEN_REGIONE"].apply(normalize_region_name)

# Map normalized keys back to Italian names 
region_name_map = {
    "piemonte": "Piemonte",
    "valledaosta": "Valle d’Aosta",
    "lombardia": "Lombardia",
    "trentinoaltoadige": "Trentino-Alto Adige",
    "veneto": "Veneto",
    "friuliveneziagiulia": "Friuli-Venezia Giulia",
    "liguria": "Liguria",
    "emiliaromagna": "Emilia-Romagna",
    "toscana": "Toscana",
    "umbria": "Umbria",
    "marche": "Marche",
    "lazio": "Lazio",
    "abruzzo": "Abruzzo",
    "molise": "Molise",
    "campania": "Campania",
    "puglia": "Puglia",
    "basilicata": "Basilicata",
    "calabria": "Calabria",
    "sicilia": "Sicilia",
    "sardegna": "Sardegna"
}
df["DEN_REGIONE_CLEAN"] = df["REGION_KEY"].map(region_name_map)

# Convert date columns to datetime
date_cols = [
    "DATA_INIZIO_PREV_STUDIO_FATT",
    "OC_DATA_INIZIO_PROGETTO",
    "OC_DATA_FINE_PROGETTO_EFFETTIVA"
]
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")
    
#  FILTER for years 2014–2024 
mask = df['OC_DATA_INIZIO_PROGETTO'].dt.year.between(2014, 2024)
df = df[mask]

# Remove dots as thousand separators and replace comma with dot for decimals
df["FINANZ_TOTALE_PUBBLICO"] = (
    df["FINANZ_TOTALE_PUBBLICO"]
    .str.replace(".", "", regex=False)  # remove thousand separators
    .str.replace(",", ".", regex=False) # convert decimal comma to dot
)

# Convert to float
df["FINANZ_TOTALE_PUBBLICO"] = pd.to_numeric(
    df["FINANZ_TOTALE_PUBBLICO"], errors="coerce"
)

#  Funding allocation by region 
funding_by_region = (
    df.groupby("DEN_REGIONE_CLEAN")["FINANZ_TOTALE_PUBBLICO"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

# Visualization: Total funding by region 
plt.figure(figsize=(10, 6))
ax = sns.barplot(
    data=funding_by_region,
    y="DEN_REGIONE_CLEAN",
    x="FINANZ_TOTALE_PUBBLICO",
    hue="DEN_REGIONE_CLEAN",
    palette="mako",
    legend=False
)


from matplotlib.ticker import FuncFormatter
# Custom formatter for K / M 
def millions_formatter(x, pos):
    if x >= 1e6:
        return f'{x*1e-6:.1f}M'  # millions
    elif x >= 1e3:
        return f'{x*1e-3:.0f}K'  # thousands
    else:
        return f'{x:.0f}'

ax.xaxis.set_major_formatter(FuncFormatter(millions_formatter))

plt.title("fig.3: Total Public Funding Allocated to Regions (2014-2024)", fontsize=14, weight="bold")
plt.xlabel("Total Public Funding (€)")
plt.ylabel("Regions")
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()

"""
import mpld3
mpld3.save_html(plt.gcf(), "graphs/funding_barchart_10years.html")

"""
plt.show()

**Heatmap on yearly funding of projects of each region in Italy** - fig.4.1

In [ ]:
# fig.4.1

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import matplotlib.ticker as mticker
import numpy as np

# Load csv
file_path = "data/open_coesione.csv"
df = pd.read_csv(file_path, dtype=str)

# FINANZ_TOTALE_PUBBLICO column
fin_col = "FINANZ_TOTALE_PUBBLICO"

# --- Convert financing to numeric ---
df[fin_col] = (
    df[fin_col].astype(str)
    .str.replace(r"[^\d,.\-]", "", regex=True)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
)
df[fin_col] = pd.to_numeric(df[fin_col], errors="coerce")

#  Drop rows without province info 
df = df[df['DEN_PROVINCIA'].notna() & (df['DEN_PROVINCIA'].str.strip() != "")]

# Handle multi-region 
df['num_regions'] = df['DEN_REGIONE'].str.split(":::").str.len()
df_expanded = df.assign(DEN_REGIONE=df['DEN_REGIONE'].str.split(":::")).explode('DEN_REGIONE')
df_expanded['DEN_REGIONE'] = df_expanded['DEN_REGIONE'].str.strip()
df_expanded[fin_col] = df_expanded[fin_col] / df_expanded['num_regions']

# Normalize region names 
region_map = {
    "TRENTINO-ALTO ADIGE": "TRENTINO-ALTO ADIGE/SÜDTIROL",
    "TRENTINO ALTO ADIGE": "TRENTINO-ALTO ADIGE/SÜDTIROL",
    "VALLE D’AOSTA": "VALLE D'AOSTA",
    "FRIULI VENEZIA GIULIA": "FRIULI-VENEZIA GIULIA",
}
df_expanded['DEN_REGIONE'] = df_expanded['DEN_REGIONE'].replace(region_map)

# Drop non-regions
to_drop = ["PAESI EUROPEI", "AMBITO NAZIONALE"]
df_expanded = df_expanded[~df_expanded['DEN_REGIONE'].isin(to_drop)]

# Extract project start year 
df_expanded['OC_DATA_INIZIO_PROGETTO'] = pd.to_datetime(
    df_expanded['OC_DATA_INIZIO_PROGETTO'], errors="coerce"
)
df_expanded['YEAR'] = df_expanded['OC_DATA_INIZIO_PROGETTO'].dt.year.astype('Int64')
df_expanded = df_expanded[(df_expanded['YEAR'] >= 2014) & (df_expanded['YEAR'] <= 2024)]

# Aggregate funding by Region × Year
funding_matrix = df_expanded.groupby(['DEN_REGIONE', 'YEAR'])[fin_col].sum().reset_index()
heatmap_data = funding_matrix.pivot(index='DEN_REGIONE', columns='YEAR', values=fin_col).fillna(0)

# Create custom annotation mask
annot_data = heatmap_data.copy()

# Keep labels only where values > 100 million, otherwise blank
annot_data = annot_data.map(lambda x: f"{x:,.0f}" if x > 100_000_000 else "")

#  Plot Heatmap (log scale and legend)
plt.figure(figsize=(14, 8))
sns.heatmap(
    heatmap_data,
    cmap="Blues",
    linewidths=0.5,
    linecolor="gray",
    norm=LogNorm(vmin=heatmap_data[heatmap_data>0].min().min(), vmax=heatmap_data.max().max()),
    cbar_kws={
        'label': 'Total Public Funding (€)',
        'format': mticker.StrMethodFormatter('{x:,.0f}')  # show thousands separators
    },
    annot=annot_data,          # custom annotations
    fmt="",           
    annot_kws={"size": 7, "color": "black"}  # styling
)

plt.title("fig.4.1: Total Public Funding per Region (2014–2024)", fontsize=16, pad=20)
plt.xlabel("Year")
plt.ylabel("Region")
plt.tight_layout()
plt.show()

**Heatmap on the funding for the selected years- with the percentage share (of total yearly funding) for the top-funded region in each year** - fig.4.2

In [ ]:
# fig.4.2

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import matplotlib.ticker as mticker
import numpy as np

# Load csv 
file_path = "data/open_coesione.csv"
df = pd.read_csv(file_path, dtype=str)

# Financing column
fin_col = "FINANZ_TOTALE_PUBBLICO"

# Convert to numeric
df[fin_col] = (
    df[fin_col].astype(str)
    .str.replace(r"[^\d,.\-]", "", regex=True)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
)
df[fin_col] = pd.to_numeric(df[fin_col], errors="coerce")

# Drop rows without province info 
df = df[df['DEN_PROVINCIA'].notna() & (df['DEN_PROVINCIA'].str.strip() != "")]

#  Handle multi-region 
df['num_regions'] = df['DEN_REGIONE'].str.split(":::").str.len()
df_expanded = df.assign(DEN_REGIONE=df['DEN_REGIONE'].str.split(":::")).explode('DEN_REGIONE')
df_expanded['DEN_REGIONE'] = df_expanded['DEN_REGIONE'].str.strip()
df_expanded[fin_col] = df_expanded[fin_col] / df_expanded['num_regions']

# Normalize region names 
region_map = {
    "TRENTINO-ALTO ADIGE": "TRENTINO-ALTO ADIGE/SÜDTIROL",
    "TRENTINO ALTO ADIGE": "TRENTINO-ALTO ADIGE/SÜDTIROL",
    "VALLE D’AOSTA": "VALLE D'AOSTA",
    "FRIULI VENEZIA GIULIA": "FRIULI-VENEZIA GIULIA",
}
df_expanded['DEN_REGIONE'] = df_expanded['DEN_REGIONE'].replace(region_map)

# Drop non-regions
to_drop = ["PAESI EUROPEI", "AMBITO NAZIONALE"]
df_expanded = df_expanded[~df_expanded['DEN_REGIONE'].isin(to_drop)]

#  Extract project start year 
df_expanded['OC_DATA_INIZIO_PROGETTO'] = pd.to_datetime(
    df_expanded['OC_DATA_INIZIO_PROGETTO'], errors="coerce"
)
df_expanded['YEAR'] = df_expanded['OC_DATA_INIZIO_PROGETTO'].dt.year.astype('Int64')

#  Filter 5 selected years 
selected_years = [2016, 2017, 2018, 2019, 2022]
df_expanded = df_expanded[df_expanded['YEAR'].isin(selected_years)]

# Aggregate funding by Region × Year 
funding_matrix = df_expanded.groupby(['DEN_REGIONE', 'YEAR'])[fin_col].sum().reset_index()
heatmap_data = funding_matrix.pivot(index='DEN_REGIONE', columns='YEAR', values=fin_col).fillna(0)

#  Create annotation for only top-funded region per year 
annot_data = pd.DataFrame("", index=heatmap_data.index, columns=heatmap_data.columns)

for year in heatmap_data.columns:
    year_data = heatmap_data[year]
    total_funding = year_data.sum()
    if total_funding > 0:
        top_region = year_data.idxmax()
        top_value = year_data[top_region]
        share_percent = (top_value / total_funding) * 100
        annot_data.loc[top_region, year] = f"{share_percent:.1f}%"

#  Plot Heatmap (log scale and legend)
plt.figure(figsize=(14, 8))
sns.heatmap(
    heatmap_data,
    cmap="Blues",
    linewidths=0.5,
    linecolor="gray",
    norm=LogNorm(vmin=heatmap_data[heatmap_data>0].min().min(), vmax=heatmap_data.max().max()),
    cbar_kws={
        'label': 'Total Public Funding (€)',
        'format': mticker.StrMethodFormatter('{x:,.0f}')
    },
    annot=annot_data,       # show only top region shares
    fmt="",
    annot_kws={"size": 8, "color": "black", "weight": "bold"}
)

plt.title("fig.4.2: Total Public Funding per Region (Top 5 Years)\n(top region per year shown as share of yearly total)", fontsize=15, pad=20)
plt.xlabel("Year")
plt.ylabel("Region")
plt.tight_layout()

"""
import mpld3
mpld3.save_html(plt.gcf(), "graphs/funding_heatmap_top5year.html")

"""
plt.show()

In [ ]:
import pandas as pd

df = pd.read_csv("data/mic_visitors.csv")
df.head()

**Horizontal barchart for total yearly museum visitors grouped by months** - fig.5

In [ ]:
# fig.5

import pandas as pd
import plotly.graph_objects as go

# Load csv
df = pd.read_csv("data/mic_visitors.csv")

# Remove Totale_regione rows
first_col = df.columns[0]
df = df[~df[first_col].str.startswith("Totale_regione_", na=False)]

# Clean and normalize data
df['Month'] = df[first_col]
df['Totale'] = df['Totale complessivo'].fillna('0').astype(str).str.replace(r'[^\d]', '', regex=True).astype(int)
df['Year'] = df['Month'].str[-4:]
df['MonthName'] = df['Month'].str.split("_").str[0]

# Month ordering
month_order = [
    "Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno",
    "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"
]

# Global x-axis max
global_max = df['Totale'].max()

# Unique years
years = sorted(df['Year'].unique())

# Create traces for each year
traces = []
for i, year in enumerate(years):
    subset = df[df['Year'] == year].copy()
    # Order months Jan→Dec
    subset['MonthName'] = pd.Categorical(subset['MonthName'], categories=month_order, ordered=True)
    subset = subset.sort_values('MonthName')
    
    traces.append(go.Bar(
        x=subset['Totale'],
        y=subset['MonthName'],
        orientation='h',
        name=year,
        visible=(i==0)  # only first year visible initially
    ))

# Dropdown buttons
buttons = []
for i, year in enumerate(years):
    visible = [False] * len(years)
    visible[i] = True
    buttons.append(dict(
        label=year,
        method="update",
        args=[{"visible": visible}, {"title": f"Museum Visitors in {year}"}]
    ))

# Layout with fixed x-axis, axis arrows
layout = go.Layout(
    barmode='group',
    xaxis=dict(
        title='Number of Visitors',
        showline=True,
        linecolor='#333',
        linewidth=2,
        showgrid=True,
        gridcolor='#ccc',
        zeroline=True,
        zerolinecolor='#333',
        tickfont=dict(size=12),
        range=[0, global_max*1.05]  # fixed x-axis
    ),
    yaxis=dict(
        autorange='reversed',
        categoryorder='array',
        categoryarray=month_order,
        showline=True,
        linecolor='#333',
        linewidth=2,
        showgrid=False,
        tickfont=dict(size=12)
    ),
    margin=dict(l=120, t=70, r=50, b=50),
    title=dict(text=f"fig.5: Museum Visitors in {years[0]}", x=0.5, xanchor="center", font=dict(size=20)),
    plot_bgcolor="#fff",
    paper_bgcolor="#fff",
    annotations=[
        # X-axis arrow
        dict(
            x=1.02, y=0, ax=0, ay=0,
            xref='paper', yref='paper',
            showarrow=True, arrowhead=3,
            arrowsize=1, arrowwidth=2, arrowcolor="#333"
        ),
        # Y-axis arrow
        dict(
            x=0, y=1.02, ax=0, ay=0,
            xref='paper', yref='paper',
            showarrow=True, arrowhead=3,
            arrowsize=1, arrowwidth=2, arrowcolor="#333"
        )
    ],
    updatemenus=[dict(
        buttons=buttons,
        direction='down',
        showactive=True,
        x=1.15,
        y=1.15
    )]
)

# Plot figure
fig = go.Figure(data=traces, layout=layout)
fig.show()
#fig.write_html("graphs/monthly_museum_visitors_10years.html")

**Bubblemap on the Yearly Number of Visitors for Each Italian Region** - fig.6.1 /fig.6.2

In [ ]:
# fig.6.1/fig.6.2

import pandas as pd
import geopandas as gpd
import folium
from ipywidgets import interact, Dropdown
from IPython.display import display

#  Normalize names 
def normalize_region_name(name: str) -> str:
    if not isinstance(name, str):
        return ""
    normalized = "".join(ch for ch in name.lower() if ch.isalnum())
    if "trentino" in normalized:
        normalized = "trentinoaltoadige"
    if "valle" in normalized:
        normalized = "valledaosta"
    return normalized

# Load data 
df = pd.read_csv("data/mic_visitors.csv", dtype=str)
gdf = gpd.read_file("data/italy_regions.geojson")

# Keep only yearly totals rows
df = df[df["Unnamed: 0"].astype(str).str.contains("Totale_regione_", na=False)].copy()

# Extract Year column
df["Year"] = df["Unnamed: 0"].str.extract(r"Totale_regione_(\d{4})")
# If extraction failed for some rows, they will be NaN — convert to numeric
df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")

# Define region columns (exclude Unnamed: 0 and Totale complessivo and Year) ---
numeric_cols = [c for c in df.columns if c not in ["Unnamed: 0", "Totale complessivo", "Year"]]

# Numeric cleaning function
def clean_numeric_series(s):
    # s is string series: remove dots used as thousands sep, replace comma decimal, strip spaces
    s_clean = s.fillna("0").astype(str).str.strip()
    # Remove any non-digit except comma and minus and dot (we will remove dots anyway)
    # First remove thousands dots
    s_clean = s_clean.str.replace(".", "", regex=False)
    # Replace comma decimal with dot (if present)
    s_clean = s_clean.str.replace(",", ".", regex=False)
    # Remove any stray non-numeric characters (except digits, dot, minus)
    s_clean = s_clean.str.replace(r"[^\d\.\-]", "", regex=True)
    # Convert to numeric coercing errors to NaN
    return pd.to_numeric(s_clean, errors="coerce")

# Apply cleaning to numeric columns
for col in numeric_cols:
    df[col] = clean_numeric_series(df[col])
    
# Ensure Totale complessivo exists and numeric
if "Totale complessivo" not in df.columns:
    raise KeyError("Column 'Totale complessivo' not found in dataframe columns.")
if not pd.api.types.is_numeric_dtype(df["Totale complessivo"]):
    df["Totale complessivo"] = clean_numeric_series(df["Totale complessivo"])
    
# Define region columns (exclude Unnamed: 0 and Totale complessivo and Year) ---
region_cols = [c for c in df.columns if c not in ["Unnamed: 0", "Totale complessivo", "Year"]]

# Reshape to long format (Year, Region, Visitors) 
long_df = df.melt(id_vars=["Year", "Totale complessivo"], var_name="Region", value_name="Visitors")

# Map Totale complessivo to each row explicitly and clean the column name
long_df = long_df.rename(columns={"Totale complessivo": "TotalYear"})

# Convert Visitors and TotalYear to numeric explicitly (again, defensive) ---
long_df["Visitors"] = pd.to_numeric(long_df["Visitors"], errors="coerce").fillna(0.0)
long_df["TotalYear"] = pd.to_numeric(long_df["TotalYear"], errors="coerce").fillna(0.0)

# Normalize region names ---
long_df["region_norm"] = long_df["Region"].apply(normalize_region_name)

# Compute Percentage relative to TotalYear
def safe_percentage(visitors, total):
    if pd.isna(total) or total == 0:
        return 0.0
    return (visitors / total) * 100.0

long_df["Percentage"] = long_df.apply(lambda r: safe_percentage(r["Visitors"], r["TotalYear"]), axis=1)

# Normalize GeoDataFrame
if "name" in gdf.columns:
    name_col = "name"
elif "reg_name" in gdf.columns:
    name_col = "reg_name"
else:
    raise KeyError("Could not find a region name column.")

gdf["region_norm"] = gdf[name_col].apply(normalize_region_name)

#  Fixed color and opacity 
fixed_color = "#3186cc"
fixed_opacity = 0.6

#  Circle size scaling 
max_visitors = long_df["Visitors"].max() if not long_df["Visitors"].isna().all() else 1.0
min_radius = 4
max_radius = 30

def scale_radius(visitors):
    """Scale visitors to circle radius with perceptual adjustment (square root scaling)."""
    if visitors <= 0 or pd.isna(visitors):
        return 0
    scaled = (visitors / max_visitors) ** 0.5
    return min_radius + scaled * (max_radius - min_radius)

# Draw map for a given year 
def draw_map(selected_year=2014):
    selected_year = int(selected_year)
    m = folium.Map(location=[41.87194, 12.56738], zoom_start=5.5, tiles="cartodbpositron")
    
    year_df = long_df[long_df["Year"] == selected_year].set_index("region_norm")
    
    if year_df.empty:
        folium.map.Marker(
            [41.87194, 12.56738],
            popup=f"No Totale_regione row found for year {selected_year}",
        ).add_to(m)
        return m
    
    for _, row in gdf.iterrows():
        region = row["region_norm"]
        if region not in year_df.index:
            continue
        visitors = year_df.loc[region, "Visitors"]
        if visitors == 0 or pd.isna(visitors):
            continue
        percentage = year_df.loc[region, "Percentage"]
        centroid = row.geometry.centroid
        
        folium.CircleMarker(
            location=[centroid.y, centroid.x],
            radius=scale_radius(visitors),
            color=fixed_color,
            fill=True,
            fill_color=fixed_color,
            fill_opacity=fixed_opacity,
            popup=f"<b>{row[name_col]}</b><br>"
                  f"Year: {selected_year}<br>"
                  f"Visitors: {int(visitors):,} ({percentage:.1f}%)"
        ).add_to(m)
    
    display(m)
   
# Dropdown 2014-2024
year_dropdown = Dropdown(options=list(range(2014, 2025)), value=2014, description="Year:")


# Dropdown 2016–2019 and 2022
#filtered_years = [y for y in [2016, 2017, 2018, 2019, 2022] if y in long_df["Year"].unique()]
#year_dropdown = Dropdown(options=sorted(filtered_years),value=filtered_years[0],description="Year:")
interact(draw_map, selected_year=year_dropdown);

**Stacked barchart of the Top 5 regions in number of visitors in the selected years** - fig.7

In [ ]:
# fig.7

import pandas as pd
import plotly.express as px

#  Load csv 
file_path = "data/mic_visitors.csv"
df = pd.read_csv(file_path)

# Keep only yearly totals 
df = df[df['Unnamed: 0'].str.contains('Totale_regione_', na=False)]

# Extract year from "Totale_regione_  " 
df['Year'] = df['Unnamed: 0'].str.extract(r'Totale_regione_(\d{4})').astype(int)

# Define region columns (exclude Totale complessivo) 
region_cols = [c for c in df.columns if c not in ['Unnamed: 0', 'Totale complessivo', 'Year']]

# Convert numbers: "1.379.306" → 1379306 
for col in region_cols + ['Totale complessivo']:
    df[col] = df[col].astype(str).str.replace('.', '', regex=False).astype(float)

# Filter for selected years 
years_to_show = [2016, 2017, 2018, 2019, 2022]
df = df[df['Year'].isin(years_to_show)]

# Convert to percentages
percent_df = df.copy()
for col in region_cols:
    percent_df[col] = (df[col] / df['Totale complessivo']) * 100
    
# Build Top 5 + "Other Regions"
data_long = []
for _, row in percent_df.iterrows():
    year = row['Year']
    regions = row[region_cols].sort_values(ascending=False)
    top5 = regions.head(5)
    others = regions.iloc[5:].sum()
    combined = top5.to_dict()
    combined['Other Regions'] = others
    combined['Year'] = year
    data_long.append(combined)

stacked_df = pd.DataFrame(data_long)

# Melt for Plotly 
stacked_df = stacked_df.melt(id_vars='Year', var_name='Region', value_name='Percentage')

# Define color palette 
# 5 shades of blue for top regions + one gray for "Other Regions"
color_map = {
    "Other Regions": "#A0A0A0",  # gray
}
# blue shades 
blue_shades = ['#08306B', '#08519C', '#2171B5', '#4292C6', '#6BAED6']

# assign blue colors to top regions 
unique_regions = [r for r in stacked_df['Region'].unique() if r != 'Other Regions']
for i, r in enumerate(unique_regions):
    color_map[r] = blue_shades[i % len(blue_shades)]

# Plot 
fig = px.bar(
    stacked_df,
    y='Year',
    x='Percentage',
    color='Region',
    orientation='h',
    title="fig.7: Top 5 Regions + Others: Yearly Visitor Distribution (2016–2019, 2022)",
    text='Percentage',
    color_discrete_map=color_map
)

fig.update_layout(
    xaxis_title="Percentage of Total Visitors",
    yaxis_title="Year",
    legend_title="Regions",
    template="plotly_white",
    bargap=0.15,
    height=600,
    yaxis = dict(
        tickmode='array',
        tickvals=[2016, 2017, 2018, 2019, 2022],
        ticktext=['2016', '2017', '2018', '2019', '2022']
    )
)

fig.update_traces(texttemplate='%{text:.1f}%', textposition='inside')

fig.show()

**Funding/visitors regional map aligned** - fig.8

In [ ]:
# fig.8

import folium
import pandas as pd
import geopandas as gpd
import numpy as np
import re

# Helper: Normalize region names 
def normalize_region_name(name):
    if not isinstance(name, str):
        return ''
    normalized = ''.join(ch for ch in name.lower() if ch.isalnum())
    if 'trentino' in normalized:
        normalized = 'trentinoaltoadige'
    if 'valle' in normalized:
        normalized = 'valledaosta'
    return normalized

# Load data
funding_df = pd.read_csv('data/open_coesione.csv')
visitor_df = pd.read_csv('data/mic_visitors.csv')
geo_df = gpd.read_file('data/italy_regions.geojson')

# Detect region name column in GeoJSON 
possible_name_cols = ['name', 'reg_name', 'REGIONE', 'DEN_REG', 'DENOMINAZI']
name_col = next((c for c in possible_name_cols if c in geo_df.columns), None)

if name_col is None:
    raise ValueError(f"Could not find a region name column in GeoJSON. Found columns: {geo_df.columns.tolist()}")

# Clean funding data 
def clean_number(x):
    if pd.isna(x):
        return 0
    x = str(x).replace('.', '').replace(',', '.')
    try:
        return float(x)
    except ValueError:
        return 0

funding_df['FINANZ_TOTALE_PUBBLICO'] = funding_df['FINANZ_TOTALE_PUBBLICO'].apply(clean_number)
funding_df['region_norm'] = funding_df['DEN_REGIONE'].apply(normalize_region_name)

funding_region_data = funding_df.groupby('region_norm')['FINANZ_TOTALE_PUBBLICO'].sum().to_dict()

# Add normalized names to GeoJSON 
geo_df['region_norm'] = geo_df[name_col].apply(normalize_region_name)

# Prepare visitor data 
long_data = []
for i, row in visitor_df.iterrows():
    year_match = None
    if isinstance(row['Unnamed: 0'], str):
        m = re.search(r'\d{4}', row['Unnamed: 0'])
        if m:
            year_match = int(m.group(0))
    for region, value in row.items():
        if region == 'Unnamed: 0':
            continue
        v = clean_number(value)
        long_data.append({
            'Year': year_match,
            'Region': region,
            'Visitors': v,
            'region_norm': normalize_region_name(region)
        })

long_df = pd.DataFrame(long_data)
years = sorted(long_df['Year'].dropna().unique())

# Create base map 
m = folium.Map(location=[41.87194, 12.56738], zoom_start=5.5, tiles='CartoDB positron')

# Funding choropleth layer 
folium.Choropleth(
    geo_data=geo_df,
    data=pd.DataFrame({'region_norm': list(funding_region_data.keys()), 'Funding': list(funding_region_data.values())}),
    columns=['region_norm', 'Funding'],
    key_on='feature.properties.region_norm',
    fill_color='YlOrRd',
    fill_opacity=0.6,
    line_opacity=0.5,
    legend_name='Funding (€)'
).add_to(m)

# Visitor circles for first year 
selected_year = years[0]
year_data = long_df[long_df['Year'] == selected_year]
total_visitors = year_data['Visitors'].sum()
max_visitors = year_data['Visitors'].max()

def scale_radius(v):
    min_radius, max_radius = 4, 25
    return 0 if v <= 0 else min_radius + np.sqrt(v / max_visitors) * (max_radius - min_radius)

for _, region in geo_df.iterrows():
    norm = region['region_norm']
    visitors = year_data.loc[year_data['region_norm'] == norm, 'Visitors'].sum()
    if visitors <= 0:
        continue
    centroid = region.geometry.centroid
    percentage = (visitors / total_visitors) * 100 if total_visitors > 0 else 0
    folium.CircleMarker(
        location=[centroid.y, centroid.x],
        radius=scale_radius(visitors),
        color='#3186cc',
        fill=True,
        fill_opacity=0.7,
        popup=f"<b>{region[name_col]}</b><br>Year: {selected_year}<br>Visitors: {int(visitors):,} ({percentage:.1f}%)"
    ).add_to(m)

# Add layer control 
folium.LayerControl().add_to(m)

# Display map in Jupyter 
m

**Mapping the early/delayed projects** - fig.9

In [ ]:
# fig.9

import pandas as pd

df = pd.read_csv("data/open_coesione.csv", dtype=str)

# Convert date columns
df["DATA_INIZIO_PREV_STUDIO_FATT"] = pd.to_datetime(df["DATA_INIZIO_PREV_STUDIO_FATT"], errors="coerce")
df["OC_DATA_INIZIO_PROGETTO"] = pd.to_datetime(df["OC_DATA_INIZIO_PROGETTO"], errors="coerce")

# Extract years
df["year_prev"] = df["DATA_INIZIO_PREV_STUDIO_FATT"].dt.year
df["year_actual"] = df["OC_DATA_INIZIO_PROGETTO"].dt.year

# Calculate delay
df["delay_years"] = df["year_actual"] - df["year_prev"]

# Show some negative delays
negative_delays = df[df["delay_years"] < 0][["CUP", "DATA_INIZIO_PREV_STUDIO_FATT", "OC_DATA_INIZIO_PROGETTO", "year_prev", "year_actual", "delay_years"]]
print(negative_delays.head())

#### **The barchart of delayed projects by region (the whole dataset)** - fig.9

In [ ]:
# fig.9

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#  Load dataset 
file_path = "data/open_coesione.csv"
df = pd.read_csv(file_path, dtype=str)

#  Keep only relevant columns 
cols = [
    "CUP",
    "DATA_INIZIO_PREV_STUDIO_FATT",
    "OC_DATA_INIZIO_PROGETTO",
    "OC_DATA_FINE_PROGETTO_EFFETTIVA",
    "DEN_REGIONE",
    "FINANZ_TOTALE_PUBBLICO"
]
df = df[cols].copy()

# Helper: normalize region names 
def normalize_region_name(name: str) -> str:
    if not isinstance(name, str):
        return ""
    normalized = "".join(ch for ch in name.lower() if ch.isalnum())
    if "trentino" in normalized or "bolzano" in normalized or "altoadige" in normalized:
        return "trentinoaltoadige"
    elif "friuli" in normalized:
        return "friuliveneziagiulia"
    elif "valledaosta" in normalized or "aoste" in normalized:
        return "valledaosta"
    elif "emiliaromagna" in normalized:
        return "emiliaromagna"
    elif "lombardia" in normalized:
        return "lombardia"
    elif "piemonte" in normalized:
        return "piemonte"
    elif "veneto" in normalized:
        return "veneto"
    elif "liguria" in normalized:
        return "liguria"
    elif "toscana" in normalized:
        return "toscana"
    elif "umbria" in normalized:
        return "umbria"
    elif "marche" in normalized:
        return "marche"
    elif "lazio" in normalized:
        return "lazio"
    elif "abruzzo" in normalized:
        return "abruzzo"
    elif "molise" in normalized:
        return "molise"
    elif "campania" in normalized:
        return "campania"
    elif "puglia" in normalized:
        return "puglia"
    elif "basilicata" in normalized:
        return "basilicata"
    elif "calabria" in normalized:
        return "calabria"
    elif "sicilia" in normalized:
        return "sicilia"
    elif "sardegna" in normalized:
        return "sardegna"
    return normalized

#  Apply normalization 
df["REGION_KEY"] = df["DEN_REGIONE"].apply(normalize_region_name)

# Map normalized keys back to Italian names 
region_name_map = {
    "piemonte": "Piemonte",
    "valledaosta": "Valle d’Aosta",
    "lombardia": "Lombardia",
    "trentinoaltoadige": "Trentino-Alto Adige",
    "veneto": "Veneto",
    "friuliveneziagiulia": "Friuli-Venezia Giulia",
    "liguria": "Liguria",
    "emiliaromagna": "Emilia-Romagna",
    "toscana": "Toscana",
    "umbria": "Umbria",
    "marche": "Marche",
    "lazio": "Lazio",
    "abruzzo": "Abruzzo",
    "molise": "Molise",
    "campania": "Campania",
    "puglia": "Puglia",
    "basilicata": "Basilicata",
    "calabria": "Calabria",
    "sicilia": "Sicilia",
    "sardegna": "Sardegna"
}
df["DEN_REGIONE_CLEAN"] = df["REGION_KEY"].map(region_name_map)

#  Convert date columns to datetime 
for col in ["DATA_INIZIO_PREV_STUDIO_FATT", "OC_DATA_INIZIO_PROGETTO", "OC_DATA_FINE_PROGETTO_EFFETTIVA"]:
    df[col] = pd.to_datetime(df[col], errors='coerce')
    
#  FILTER for years 2014–2024 
mask = df['OC_DATA_INIZIO_PROGETTO'].dt.year.between(2014, 2024)
df = df[mask]

# Extract years 
df["year_prev"] = df["DATA_INIZIO_PREV_STUDIO_FATT"].dt.year
df["year_actual"] = df["OC_DATA_INIZIO_PROGETTO"].dt.year

# Split DataFrames: same vs delayed projects ---
same_year_df = df[df["year_prev"] == df["year_actual"]].copy()
delayed_df = df[df["year_prev"] != df["year_actual"]].copy()

print(f"Projects with same expected and actual start year: {len(same_year_df)}")
print(f"Projects with different expected and actual start year: {len(delayed_df)}")

# Calculate delay in years 
delayed_df["delay_years"] = delayed_df["year_actual"] - delayed_df["year_prev"]

#  Funding to numeric 
df["FINANZ_TOTALE_PUBBLICO"] = (
    df["FINANZ_TOTALE_PUBBLICO"]
    .str.replace(",", ".", regex=False)
    .astype(float, errors="ignore")
)

#  Average delay (overall) ---
average_delay = delayed_df["delay_years"].mean()
print(f"\nAverage project delay (years): {average_delay:.2f}")

#  Average delay by region (clean Italian names) 
avg_delay_by_region = (
    delayed_df.groupby("DEN_REGIONE_CLEAN")["delay_years"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

#  Funding allocation by region 
funding_by_region = (
    df.groupby("DEN_REGIONE_CLEAN")["FINANZ_TOTALE_PUBBLICO"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

#  Merge for summary 
region_summary = pd.merge(avg_delay_by_region, funding_by_region, on="DEN_REGIONE_CLEAN", how="left")

print("\nRegional summary (average delay + total funding):")
print(region_summary.head())

# --- Plotly bar chart ---
fig = px.bar(
    avg_delay_by_region,
    x="delay_years",
    y="DEN_REGIONE_CLEAN",
    orientation="h",
    text="delay_years",
    labels={"delay_years": "Average Delay (years)", "DEN_REGIONE_CLEAN": "Region"},
    title="fig.9: Average Delay of Projects per Region (2014–2024)",
    height=600
)

fig.update_traces(
    texttemplate="%{text:.2f}",
    textposition="outside",
    marker_color="teal"
)
fig.update_layout(yaxis=dict(autorange="reversed"))  # Largest delay on top

# --- Show and save as interactive HTML in one line ---
fig.show()  
#fig.write_html("graphs/regional_average_delay.html")

**The piechart of the projects' timeliness (2014-2024)** - fig.10

In [ ]:
# fig.10

#filtro oc_data_inizio_progetto 2014-1024
#filtra prev_studio_fatt sameyear, early, delayed
import pandas as pd
from matplotlib import pyplot as plt

all_project = pd.read_csv("data/open_coesione.csv")
date_columns = ['DATA_INIZIO_PREV_STUDIO_FATT','OC_DATA_INIZIO_PROGETTO','OC_DATA_FINE_PROGETTO_EFFETTIVA']
all_project['DATA_INIZIO_PREV_STUDIO_FATT'] = pd.to_datetime(all_project['DATA_INIZIO_PREV_STUDIO_FATT'])
all_project['OC_DATA_INIZIO_PROGETTO'] = pd.to_datetime(all_project['OC_DATA_INIZIO_PROGETTO'])
all_project['OC_DATA_FINE_PROGETTO_EFFETTIVA'] = pd.to_datetime(all_project['OC_DATA_FINE_PROGETTO_EFFETTIVA'])
time_section = all_project.loc[(all_project["OC_DATA_INIZIO_PROGETTO"].dt.year >= 2014) & (all_project["OC_DATA_INIZIO_PROGETTO"].dt.year <= 2024)].copy()
time_section

In [ ]:
# Helper: normalize region names 
def normalize_region_name(name: str) -> str:
    if not isinstance(name, str):
        return ""
    normalized = "".join(ch for ch in name.lower() if ch.isalnum())
    if "trentino" in normalized or "bolzano" in normalized or "altoadige" in normalized:
        return "trentinoaltoadige"
    elif "friuli" in normalized:
        return "friuliveneziagiulia"
    elif "valledaosta" in normalized or "aoste" in normalized:
        return "valledaosta"
    elif "emiliaromagna" in normalized:
        return "emiliaromagna"
    elif "lombardia" in normalized:
        return "lombardia"
    elif "piemonte" in normalized:
        return "piemonte"
    elif "veneto" in normalized:
        return "veneto"
    elif "liguria" in normalized:
        return "liguria"
    elif "toscana" in normalized:
        return "toscana"
    elif "umbria" in normalized:
        return "umbria"
    elif "marche" in normalized:
        return "marche"
    elif "lazio" in normalized:
        return "lazio"
    elif "abruzzo" in normalized:
        return "abruzzo"
    elif "molise" in normalized:
        return "molise"
    elif "campania" in normalized:
        return "campania"
    elif "puglia" in normalized:
        return "puglia"
    elif "basilicata" in normalized:
        return "basilicata"
    elif "calabria" in normalized:
        return "calabria"
    elif "sicilia" in normalized:
        return "sicilia"
    elif "sardegna" in normalized:
        return "sardegna"
    return normalized

# Apply normalization 
time_section["REGION_KEY"] = time_section["DEN_REGIONE"].apply(normalize_region_name)

# Map normalized keys back to Italian names 
region_name_map = {
    "piemonte": "Piemonte",
    "valledaosta": "Valle d’Aosta",
    "lombardia": "Lombardia",
    "trentinoaltoadige": "Trentino-Alto Adige",
    "veneto": "Veneto",
    "friuliveneziagiulia": "Friuli-Venezia Giulia",
    "liguria": "Liguria",
    "emiliaromagna": "Emilia-Romagna",
    "toscana": "Toscana",
    "umbria": "Umbria",
    "marche": "Marche",
    "lazio": "Lazio",
    "abruzzo": "Abruzzo",
    "molise": "Molise",
    "campania": "Campania",
    "puglia": "Puglia",
    "basilicata": "Basilicata",
    "calabria": "Calabria",
    "sicilia": "Sicilia",
    "sardegna": "Sardegna"
}
time_section["DEN_REGIONE_CLEAN"] = time_section["REGION_KEY"].map(region_name_map)
time_section

In [ ]:
on_time = time_section.loc[(time_section["OC_DATA_INIZIO_PROGETTO"].dt.year == time_section["DATA_INIZIO_PREV_STUDIO_FATT"].dt.year)]
# on_time 1284 progetti
delayed = time_section.loc[(time_section["OC_DATA_INIZIO_PROGETTO"].dt.year > time_section["DATA_INIZIO_PREV_STUDIO_FATT"].dt.year)]
# delayed 908 progetti
early = time_section.loc[(time_section["OC_DATA_INIZIO_PROGETTO"].dt.year < time_section["DATA_INIZIO_PREV_STUDIO_FATT"].dt.year)]
# early 580 progetti

In [ ]:
# plot the chart

pie_data = [len(on_time), len(delayed), len(early)]
pie_labels = ["On Time", "Delayed", "Early"]
total = sum(pie_data)

fig, ax = plt.subplots(figsize=(8, 6))
wedges, texts, autotexts = ax.pie(pie_data,
                               labels=pie_labels,
                               autopct='%1.0f%%',
                                wedgeprops=dict(width=0.7, edgecolor='w'),
                                colors = ["#2A63AD", "#322AAD", "#2AA5AD"]
                                 )
ax.legend(wedges,            
    pie_labels,        
    title="Project start",
    loc="center left",
    bbox_to_anchor=(1, 0.3, 0.5, 1)
)
ax.text(0, 0, f"Total: {total}", ha='center', va='center', fontsize=10)
ax.set_title("fig.10: Projects Start Timeliness")
plt.show()

In [ ]:
avg_early = (early["DATA_INIZIO_PREV_STUDIO_FATT"].dt.year - early["OC_DATA_INIZIO_PROGETTO"].dt.year).mean()
avg_early

In [ ]:
avg_late = (delayed["OC_DATA_INIZIO_PROGETTO"].dt.year - delayed["DATA_INIZIO_PREV_STUDIO_FATT"].dt.year).mean()
avg_late

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

try:
    # Load the dataset
    # The numbers use '.' for thousands and ',' for decimals.
    file_path = 'data/mic_income.csv'
    df = pd.read_csv(file_path, decimal=',', thousands='.', index_col=0)

    print("Data loaded successfully.")

    # --- Data Transformation ---
    
    # Extract the 'Year' from the index (e.g., 'Gennaio_2014' -> '2014')
    if not pd.api.types.is_datetime64_any_dtype(df.index):
        # Create a 'Year' column by splitting the index string
        df['Year'] = df.index.str.split('_').str[1]
    else:
        df['Year'] = df.index.year

    # Convert Year to integer for grouping
    df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
    
    # Drop any rows where 'Year' could not be parsed
    df.dropna(subset=['Year'], inplace=True)
    
    # Cast Year to integer
    df['Year'] = df['Year'].astype(int)
    
    # Filter for the years 2014-2024, as requested
    df_filtered = df[(df['Year'] >= 2014) & (df['Year'] <= 2024)]

    # Group by the 'Year' column and sum up the monthly values
    df_yearly = df_filtered.groupby('Year').sum(numeric_only=True)

    # For the plot, we'll exclude 'Totale complessivo'
    # Its large value would make the other regions' lines flat and unreadable.
    if 'Totale complessivo' in df_yearly.columns:
        df_plot = df_yearly.drop(columns='Totale complessivo')
    else:
        df_plot = df_yearly
        
    print("Data successfully aggregated by year.")

    # --- Plotting ---
    
    plt.figure(figsize=(15, 10))
    
    # Plot each region as a separate line
    for region in df_plot.columns:
        plt.plot(df_plot.index, df_plot[region], label=region, marker='o', markersize=4)
        
    plt.title('Total Annual Income by Region (2014-2024)', fontsize=16)
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Total Income (in Euro)', fontsize=12)
    
    # Ensure all years are shown as ticks on the x-axis
    plt.xticks(df_plot.index, rotation=45)
    
    # Format Y-axis to be more readable
    plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: format(int(x), ',')))
    
    plt.grid(True, linestyle='--', alpha=0.6)
    
    # Place the legend outside the main plot area
    plt.legend(bbox_to_anchor=(1.04, 1), loc='upper left', title="Regions")
    
    # Adjust layout to make space for the legend
    plt.tight_layout(rect=[0, 0, 0.85, 1]) 
    
    plot_filename = 'annual_income_by_region_2014_2024.png'
    plt.savefig(plot_filename)
    
    print(f"\nSuccessfully created and saved the graph as '{plot_filename}'.")

except Exception as e:
    print(f"An error occurred: {e}")